//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QAssetBundle
{
    
    public class Assetobj_1_prefab
    {
        public const string BundleName = "assetobj 1_prefab";
        public const string ASSETOBJ_1 = "AssetObj 1";
    }
    public class Assetobj_2_prefab
    {
        public const string BundleName = "assetobj 2_prefab";
        public const string ASSETOBJ_2 = "AssetObj 2";
    }
    public class Assetobj_3_prefab
    {
        public const string BundleName = "assetobj 3_prefab";
        public const string ASSETOBJ_3 = "AssetObj 3";
    }
    public class Assetobj_prefab
    {
        public const string BundleName = "assetobj_prefab";
        public const string ASSETOBJ = "AssetObj";
    }
    public class Depthlabelpanel_prefab
    {
        public const string BundleName = "depthlabelpanel_prefab";
        public const string DEPTHLABELPANEL = "DepthLabelPanel";
    }
    public class Infoitembtn_prefab
    {
        public const string BundleName = "infoitembtn_prefab";
        public const string INFOITEMBTN = "InfoItemBtn";
    }
    public class Labelitem_prefab
    {
        public const string BundleName = "labelitem_prefab";
        public const string LABELITEM = "LabelItem";
    }
    public class Sceneres_unity
    {
        public const string BundleName = "sceneres_unity";
        public const string SCENERES = "SceneRes";
    }
    public class Showresultitem_prefab
    {
        public const string BundleName = "showresultitem_prefab";
        public const string SHOWRESULTITEM = "ShowResultItem";
    }
    public class Spriteatlas_spriteatlas
    {
        public const string BundleName = "spriteatlas_spriteatlas";
        public const string SPRITEATLAS = "spriteatlas";
    }
    public class Squarea_prefab
    {
        public const string BundleName = "squarea_prefab";
        public const string SQUAREA = "SquareA";
    }
    public class Textureexample1_png
    {
        public const string BundleName = "textureexample1_png";
        public const string TEXTUREEXAMPLE1 = "TextureExample1";
    }
}
